apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-da1x
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-da1x@sha256:7d9fda0614ebbfaa4bfc9091ae711233145b44aab8ebb7d359718d1265cffeae
        name: my-nodejs
        resources: {}
status: {}
